CREATE TABLE IF NOT EXISTS public.birthdays
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       int UNIQUE               NOT NULL,
    person_name   bigint UNIQUE            NOT NULL,
    remind_at     smallint                 NOT NULL,
    reminder_type TIMESTAMP WITH TIME ZONE NOT NULL,
    comment       varchar(500)             NOT NULL,
    birthday_date TIMESTAMP WITH TIME ZONE NOT NULL
);