-- +goose Up
-- SQL in this section is executed when the migration is applied.
create table if not exists public.task_types(
    id int8 generated by default as identity not null primary key,
    name text not null
);


-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
drop table if exists public.task_types restrict